/*
 CHRISXCHANGE catalogue
 Supabase table expected: products
 Columns: business_id,name,description,price,currency,image_url,category,stock_quantity,is_available,is_featured
*/
const SUPABASE_URL="https://wopjohlkjhqymhjjxqgi.supabase.co";
const SUPABASE_ANON_KEY=window.CHRISXCHANGE_SUPABASE_ANON_KEY||"";
const state={products:[],category:"all"};
const params=new URLSearchParams(location.search);
const requestedCategory=(params.get("category")||"all").toLowerCase().trim();
const titleMap={electronics:"Electronics",phones:"Phones & Accessories",computers:"Computers",furniture:"Furniture",hardware:"Hardware",fashion:"Fashion",transport:"Transport",retail:"Retail Shop"};
function normalCategory(value){const s=String(value||"").toLowerCase();if(s.includes("phone")||s.includes("mobile"))return"phones";if(s.includes("electronic"))return"electronics";if(s.includes("computer")||s.includes("laptop")||s.includes("it"))return"computers";if(s.includes("furniture"))return"furniture";if(s.includes("hardware")||s.includes("construction"))return"hardware";if(s.includes("fashion")||s.includes("cloth")||s.includes("shoe"))return"fashion";if(s.includes("transport")||s.includes("logistic")||s.includes("vehicle"))return"transport";if(s.includes("retail")||s.includes("supermarket")||s.includes("shop"))return"retail";return s||"other"}
function money(p,c="UGX"){return new Intl.NumberFormat("en-UG",{style:"currency",currency:c||"UGX",maximumFractionDigits:0}).format(Number(p)||0)}
function escapeHtml(v){return String(v??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function renderFilters(){const cats=[...new Set(state.products.map(p=>normalCategory(p.category)))].filter(Boolean).sort();document.querySelector("#categoryFilters").innerHTML=["all",...cats].map(c=>'<button class="category-filter '+(state.category===c?"active":"")+'" data-cat="'+escapeHtml(c)+'">'+escapeHtml(c==="all"?"All":titleMap[c]||c)+'</button>').join("");document.querySelectorAll(".category-filter").forEach(b=>b.onclick=()=>{state.category=b.dataset.cat;render()})}
function render(){const q=document.querySelector("#productSearch").value.toLowerCase().trim();let list=state.products.filter(p=>{const cat=normalCategory(p.category);return (state.category==="all"||cat===state.category)&&(!q||[p.name,p.description,p.category].join(" ").toLowerCase().includes(q))});const sort=document.querySelector("#sortProducts").value;if(sort==="low")list.sort((a,b)=>Number(a.price)-Number(b.price));if(sort==="high")list.sort((a,b)=>Number(b.price)-Number(a.price));if(sort==="name")list.sort((a,b)=>String(a.name).localeCompare(String(b.name)));if(sort==="featured")list.sort((a,b)=>Number(Boolean(b.is_featured))-Number(Boolean(a.is_featured)));document.querySelector("#productGrid").innerHTML=list.length?list.map(p=>{const image=p.image_url||"https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80";return '<article class="product-card-cx"><img src="'+escapeHtml(image)+'" alt="'+escapeHtml(p.name)+'" loading="lazy" onerror="this.src=\'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=80\'"><div class="product-body"><span class="product-category">'+escapeHtml(titleMap[normalCategory(p.category)]||p.category||"Product")+'</span><h3>'+escapeHtml(p.name)+'</h3><p class="product-desc">'+escapeHtml(p.description||"Quality product available on CHRISXCHANGE.")+'</p><div class="product-price">'+money(p.price,p.currency)+'</div><div class="product-actions"><a href="store-details.html?product='+encodeURIComponent(p.name)+'">View</a><button type="button" onclick="alert(\'Product selected: '+escapeHtml(p.name).replace(/'/g,"\\'")+'\')">Contact</button></div></div></article>'}).join(""):'<div class="empty-catalogue"><i class="fa-solid fa-box-open" style="font-size:2rem"></i><h2>No products found</h2><p>Try another search or category.</p></div>';document.querySelector("#productStatus").textContent=list.length?list.length+" product"+(list.length===1?"":"s")+" found":""}
async function loadProducts(){if(!SUPABASE_ANON_KEY){document.querySelector("#productStatus").innerHTML='<strong>Catalogue connection is ready.</strong><br>One Supabase public anon key still needs to be added to <code>products.js</code> before live products can load.';return}try{const url=SUPABASE_URL+"/rest/v1/products?select=business_id,name,description,price,currency,image_url,category,stock_quantity,is_available,is_featured&is_available=eq.true";const res=await fetch(url,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:"Bearer "+SUPABASE_ANON_KEY}});if(!res.ok)throw new Error("Supabase returned "+res.status);state.products=await res.json();state.category=titleMap[requestedCategory]?requestedCategory:"all";document.querySelector("#catalogueTitle").textContent=state.category==="all"?"All Products":(titleMap[state.category]||"Products");document.querySelector("#catalogueSubtitle").textContent=state.category==="all"?"Discover products from businesses on CHRISXCHANGE.":"Browse "+(titleMap[state.category]||state.category)+" products.";renderFilters();render()}catch(e){document.querySelector("#productStatus").innerHTML="<strong>Catalogue could not load.</strong><br>"+escapeHtml(e.message)}}
document.querySelector("#productSearch").addEventListener("input",render);document.querySelector("#sortProducts").addEventListener("change",render);loadProducts();